### ISSUE TITLE
`ansible-playbook` command works, `debops -t` does not

### ISSUE THREAD

**Issue by neo-tahi** [debops/ansible-rails_deploy#20]
FYI, for some reason when I ran "debops -t myappname", it could not find my playbook with the tag "myappname", even though it was there. When I then ran "ansible-playbook ansible/playbooks/custom.yml -i ansible/inventory -t myappname", it found my playbook and started installing node and all that.

Is this a problem with the rails_deploy docs, or with the debops command line tool? Or neither? /cc @drybjed 

This isn't a big issue for us because we figured it out, but newcomers might be confused. Please feel free to close this issue, since it's primarily here for documentation.

Cheers,
@DTrejo & @Faun

**Comment by drybjed** [comment]
`debops` script does not automatically run all present playbooks. By default it will execute first "site.yml" playbook found in directories searched by the script. If you want to specify a different playbook, you need to add it, without `.yml` extension, as the first parameter of the `debops` script. In your case, that would be:

    debops custom -t myappname

This is a limitation (1st argument checked for possible playbook name), but we cannot make that possible on any parameter, since all others are passed directly to `ansible-playbook`.

**Comment by neo-tahi** [comment]
Thanks, @drybjed. The custom playbook argument was key in getting this to work.
